# Generated by Django 5.2.4 on 2026-04-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="emoji",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
