# Generated by Django 5.2.4 on 2026-04-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_specification_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specification",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
