# Generated by Django 5.2.4 on 2026-05-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_alter_cart_user_alter_cartitem_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
