# Generated by Django 5.2.4 on 2026-10-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0005_remove_cart_cart_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="session_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
