# Generated by Django 5.2.4 on 2026-10-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0006_cart_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="session_id",
            field=models.UUIDField(),
        ),
    ]
