import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/Layout/NavBar";
import { apiFetch } from "@/lib/api";
import { Category } from "@/types/api";
import Footer from "@/components/Layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const res = await apiFetch<Category[]>("api/categories/", {
    method: "GET",
    next: {
      revalidate: 3600,
      tags: ["categories"]
    }
  })

  return (
    <html
      lang="en"
    >
      <body className="antialiased">
        <NavBar categories={res}/>
        {children}
        <Footer />
        </body>
    </html>
  );
}
