import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { apiFetch } from "@/lib/api";
import { Category } from "@/types/api";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type PaginatedResponse = {
  count: number;
  results: Category[];
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const res = await apiFetch<PaginatedResponse>("api/categories/", {
    method: "GET",
    next: {
      revalidate: 3600,
      tags: ["categories"]
    }
  }).then(res => res?.results)

  return (
    <html
      lang="en"
    >
      <body className="antialiased">
        <NavBar categories={res}/>
        {children}
        </body>
    </html>
  );
}
